import "./globals.css";
import Navbar from "../components/navbar/Navbar";
import Footer from "../components/footer/footer";
import { Bebas_Neue, Roboto_Condensed } from 'next/font/google';

const bebas = Bebas_Neue({ 
  subsets: ['latin'],
  weight: '400', // Only one weight available
  variable: '--font-bebas' 
});

const roboto = Roboto_Condensed({
  subsets: ['latin'],
  weight: ['300', '400', '700'],
  variable: '--font-roboto'
});

export const metadata = {
  title: "Moto lux",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${bebas.variable} ${roboto.variable}`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
